services:
  - type: web
    name: profit-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: KEEPA_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false 