services:
  - type: docker
    name: profit-bot
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: KEEPA_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false 